# 1. Building instructions & Dynamic Proxy Generation
[build]
  # Compilamos la app y, acto seguido, inyectamos la variable cifrada en un archivo _redirects dentro de dist
  command = "npm run build && echo \"/api/* $PROXIED_BACKEND_URL/api/:splat 200!\" > dist/_redirects"
  publish = "dist"

# 2. SPA ROUTING (React Router life-jacket)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200